[build]
  publish = "public"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:; font-src 'self' https: data:; connect-src 'self' https: wss: https://*.elevenlabs.io https://elevenlabs.io; script-src 'self' https: 'unsafe-inline' 'unsafe-eval' https://elevenlabs.io https://*.elevenlabs.io; frame-src 'self' https:; worker-src 'self' blob: https://*.elevenlabs.io; child-src 'self' blob:;"

[[headers]]
  for = "/audio/*"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*" 